# Generated by Django 4.2.7 on 2023-12-11 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('busnum', models.CharField(max_length=32, unique=True)),
                ('depart', models.CharField(max_length=32)),
                ('destination', models.CharField(max_length=32)),
                ('departtime', models.CharField(max_length=32)),
                ('seats', models.IntegerField(default=35)),
                ('remained_seats', models.PositiveIntegerField(default=35)),
                ('fare', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=88)),
                ('is_admin', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='TicketInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('S', '提交'), ('I', '失效'), ('N', '正常'), ('F', '完成'), ('T', '取消')], default='S', max_length=1)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.businfo')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo')),
            ],
        ),
    ]
