# Generated by Django 4.2.7 on 2023-11-26 07:06

from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_userinfo_id_userinfo_u_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusInfo",
            fields=[
                ("b_id", models.IntegerField(primary_key=True, serialize=False)),
                ("busnum", models.CharField(max_length=32)),
                ("depart", models.CharField(max_length=32)),
                ("destination", models.CharField(max_length=32)),
                ("departtime", models.CharField(max_length=32)),
            ],
        ),
    ]
