# Generated by Django 4.2.7 on 2023-11-26 12:20

from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_businfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("u_id", models.IntegerField()),
                ("b_id", models.IntegerField()),
                ("status", models.CharField(choices=[("N", "正常"), ("F", "完成"), ("T", "取消")], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name="businfo",
            name="b_id",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="u_id",
        ),
        migrations.AddField(
            model_name="businfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, default=0, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, default=0, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
    ]
