# Generated by Django 4.2.7 on 2023-11-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ticketinfo_remove_businfo_b_id_remove_userinfo_u_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
