# Generated by Django 4.2.7 on 2023-11-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_businfo_id_alter_userinfo_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusInfo',
        ),
        migrations.DeleteModel(
            name='TicketInfo',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
