# Generated by Django 4.2.7 on 2023-11-26 13:09

from django.db import models, migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0007_delete_businfo_delete_ticketinfo_delete_userinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("busnum", models.CharField(max_length=32)),
                ("depart", models.CharField(max_length=32)),
                ("destination", models.CharField(max_length=32)),
                ("departtime", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="TicketInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("u_id", models.IntegerField()),
                ("b_id", models.IntegerField()),
                ("status", models.CharField(choices=[("N", "正常"), ("F", "完成"), ("T", "取消")], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32, unique=True)),
                ("password", models.CharField(max_length=64)),
            ],
        ),
    ]
