# Generated by Django 4.2.7 on 2023-11-26 13:12

from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="name",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
