# Generated by Django 4.2.7 on 2023-11-27 09:16

from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_businfo_busnum"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="is_admin",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
