# Generated by Django 4.2.7 on 2023-11-27 09:46

from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_userinfo_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketinfo",
            name="status",
            field=models.CharField(
                choices=[("S", "提交"), ("I", "失效"), ("N", "正常"), ("F", "完成"), ("T", "取消")],
                default="S",
                max_length=1,
            ),
        ),
    ]
