# Generated by Django 4.2.7 on 2023-11-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_ticketinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketinfo',
            name='b_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.businfo'),
        ),
        migrations.AlterField(
            model_name='ticketinfo',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo'),
        ),
    ]
