# Generated by Django 4.2.7 on 2023-11-27 10:02

import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_ticketinfo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketinfo",
            name="b_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.businfo"),
        ),
        migrations.AlterField(
            model_name="ticketinfo",
            name="u_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.userinfo"),
        ),
    ]
