# Generated by Django 4.2.7 on 2023-11-27 11:28

from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_ticketinfo_b_id_alter_ticketinfo_u_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketinfo",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
