# Generated by Django 4.2.7 on 2023-11-27 12:04

from django.db import models, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_ticketinfo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="businfo",
            name="seats",
            field=models.IntegerField(default=35),
        ),
    ]
