# Generated by Django 4.2.7 on 2023-12-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_businfo_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='businfo',
            name='fare',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='businfo',
            name='remained_seats',
            field=models.PositiveIntegerField(default=35),
        ),
    ]
