name: test-build

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-main:
    name: Docker main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Build
        uses: docker/build-push-action@v5
        if: github.event_name == 'pull_request'
        with:
          context: .
          file: ./dockerfile
          push: false
          load: true
          tags: azide/bus-reservation-backend:dummy
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test image
        uses: ./.github/actions/test-docker
        if: github.event_name == 'pull_request'
        with:
          docker-image-name: azide/bus-reservation-backend:dummy
          wait-time: 10

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Git Branch Name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: Build and push
        uses: docker/build-push-action@v5
        if: github.event_name != 'pull_request'
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: azide/bus-reservation-backend:${{ env.GIT_BRANCH_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
